CREATE DATABASE IF NOT EXISTS burgers_db;

USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers (
id INTEGER(11) AUTO_INCREMENT NOT NULL PRIMARY KEY
, burger_name VARCHAR(30) NOT NULL
, devoured BOOLEAN NOT NULL DEFAULT FALSE
, date TIMESTAMP);
